<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Accommodation;

class AccommodationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $accommodations = [
            [
                'name' => 'Grand Plaza Hotel',
                'description' => 'Luxurious 5-star hotel in the heart of New York City. Features spacious rooms with stunning city views, rooftop pool, fine dining restaurant, and state-of-the-art fitness center. Perfect for concert-goers looking for premium accommodation.',
                'type' => 'Hotel',
                'address' => '123 Broadway Avenue',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'latitude' => 40.7580,
                'longitude' => -73.9855,
                'phone' => '+1-212-555-0100',
                'email' => 'info@grandplazanyc.com',
                'website' => 'https://www.grandplazanyc.com',
                'price_per_night' => 29999.00,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Pool', 'Gym', 'Restaurant', 'Bar', 'Room Service', 'Parking', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
                    'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
                ],
                'status' => 'active',
                'featured' => true,
                'rating' => 4.8,
                'review_count' => 1250,
            ],
            [
                'name' => 'Downtown Boutique Inn',
                'description' => 'Charming boutique hotel with modern amenities and personalized service. Located within walking distance of major concert venues and entertainment districts. Enjoy complimentary breakfast and evening wine reception.',
                'type' => 'Boutique Hotel',
                'address' => '456 Fifth Avenue',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'latitude' => 40.7489,
                'longitude' => -73.9680,
                'phone' => '+1-212-555-0200',
                'email' => 'reservations@downtownboutique.com',
                'website' => 'https://www.downtownboutique.com',
                'price_per_night' => 18999.00,
                'max_guests' => 2,
                'amenities' => ['WiFi', 'Breakfast Included', 'Concierge', 'Air Conditioning', 'Mini Bar'],
                'images' => [
                    'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
                    'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
                ],
                'status' => 'active',
                'featured' => true,
                'rating' => 4.6,
                'review_count' => 856,
            ],
            [
                'name' => 'City Center Suites',
                'description' => 'Modern apartment-style suites perfect for extended stays. Each suite includes a full kitchen, separate living area, and workspace. Ideal for groups attending multiple concerts or events.',
                'type' => 'Apartment',
                'address' => '789 Park Avenue',
                'city' => 'New York',
                'state' => 'NY',
                'country' => 'USA',
                'latitude' => 40.7614,
                'longitude' => -73.9776,
                'phone' => '+1-212-555-0300',
                'email' => 'booking@citycentersuites.com',
                'website' => 'https://www.citycentersuites.com',
                'price_per_night' => 24999.00,
                'max_guests' => 6,
                'amenities' => ['WiFi', 'Kitchen', 'Washer/Dryer', 'Parking', 'Workspace', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                ],
                'status' => 'active',
                'featured' => false,
                'rating' => 4.5,
                'review_count' => 623,
            ],
            [
                'name' => 'Hollywood Star Hotel',
                'description' => 'Iconic hotel on the Hollywood Walk of Fame. Steps away from major music venues and entertainment landmarks. Features retro-modern design with all contemporary comforts.',
                'type' => 'Hotel',
                'address' => '6801 Hollywood Boulevard',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'latitude' => 34.1016,
                'longitude' => -118.3406,
                'phone' => '+1-323-555-0100',
                'email' => 'info@hollywoodstarhotel.com',
                'website' => 'https://www.hollywoodstarhotel.com',
                'price_per_night' => 21999.00,
                'max_guests' => 3,
                'amenities' => ['WiFi', 'Pool', 'Valet Parking', 'Restaurant', 'Bar', 'Spa', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800',
                    'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
                ],
                'status' => 'active',
                'featured' => true,
                'rating' => 4.7,
                'review_count' => 2100,
            ],
            [
                'name' => 'Sunset Boulevard Hostel',
                'description' => 'Budget-friendly hostel with private rooms and dorm options. Great social atmosphere perfect for solo travelers and music lovers. Regular events and meet-ups organized.',
                'type' => 'Hostel',
                'address' => '8500 Sunset Boulevard',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'latitude' => 34.0928,
                'longitude' => -118.3842,
                'phone' => '+1-323-555-0400',
                'email' => 'stay@sunsetblvdhostel.com',
                'website' => 'https://www.sunsetblvdhostel.com',
                'price_per_night' => 5999.00,
                'max_guests' => 2,
                'amenities' => ['WiFi', 'Shared Kitchen', 'Common Room', 'Lockers', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
                    'https://images.unsplash.com/photo-1587985064135-0366536eab42?w=800',
                ],
                'status' => 'active',
                'featured' => false,
                'rating' => 4.2,
                'review_count' => 445,
            ],
            [
                'name' => 'Marina Bay Resort',
                'description' => 'Beachfront resort with stunning ocean views. Perfect for concert weekends with pool parties and beach access. Multiple on-site restaurants and entertainment options.',
                'type' => 'Resort',
                'address' => '1234 Ocean Drive',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'country' => 'USA',
                'latitude' => 34.0059,
                'longitude' => -118.4961,
                'phone' => '+1-310-555-0100',
                'email' => 'reservations@marinabayresort.com',
                'website' => 'https://www.marinabayresort.com',
                'price_per_night' => 34999.00,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Pool', 'Beach Access', 'Spa', 'Restaurant', 'Bar', 'Gym', 'Parking', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800',
                    'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
                ],
                'status' => 'active',
                'featured' => true,
                'rating' => 4.9,
                'review_count' => 1876,
            ],
            [
                'name' => 'The London Music Hotel',
                'description' => 'Rock-themed hotel in the heart of London. Each room decorated with music memorabilia. Walking distance to major concert halls and the West End theatre district.',
                'type' => 'Hotel',
                'address' => '100 Oxford Street',
                'city' => 'London',
                'state' => 'England',
                'country' => 'UK',
                'latitude' => 51.5154,
                'longitude' => -0.1419,
                'phone' => '+44-20-7946-0100',
                'email' => 'info@londonmusichotel.co.uk',
                'website' => 'https://www.londonmusichotel.co.uk',
                'price_per_night' => 17999.00,
                'max_guests' => 2,
                'amenities' => ['WiFi', 'Bar', 'Restaurant', 'Concierge', 'Air Conditioning', 'Music Library'],
                'images' => [
                    'https://images.unsplash.com/photo-1568084680786-a84340ff52e4?w=800',
                    'https://images.unsplash.com/photo-1596436889106-be35e843f974?w=800',
                ],
                'status' => 'active',
                'featured' => false,
                'rating' => 4.4,
                'review_count' => 932,
            ],
            [
                'name' => 'South Beach Art Deco Hotel',
                'description' => 'Iconic Art Deco hotel on Miami Beach. Steps from the sand and nightlife. Famous for hosting celebrities and music artists. Rooftop pool with ocean views.',
                'type' => 'Hotel',
                'address' => '1500 Ocean Drive',
                'city' => 'Miami',
                'state' => 'FL',
                'country' => 'USA',
                'latitude' => 25.7907,
                'longitude' => -80.1300,
                'phone' => '+1-305-555-0100',
                'email' => 'info@southbeachdeco.com',
                'website' => 'https://www.southbeachdeco.com',
                'price_per_night' => 27999.00,
                'max_guests' => 3,
                'amenities' => ['WiFi', 'Pool', 'Beach Access', 'Restaurant', 'Bar', 'Valet Parking', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
                    'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800',
                ],
                'status' => 'active',
                'featured' => true,
                'rating' => 4.7,
                'review_count' => 1543,
            ],
            [
                'name' => 'Austin Live Music Lofts',
                'description' => 'Modern lofts in the live music capital of the world. Located on 6th Street entertainment district. Soundproof rooms perfect for musicians and concert-goers.',
                'type' => 'Apartment',
                'address' => '600 East 6th Street',
                'city' => 'Austin',
                'state' => 'TX',
                'country' => 'USA',
                'latitude' => 30.2672,
                'longitude' => -97.7431,
                'phone' => '+1-512-555-0100',
                'email' => 'stay@austinlivelofts.com',
                'website' => 'https://www.austinlivelofts.com',
                'price_per_night' => 16999.00,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Kitchen', 'Parking', 'Soundproof', 'Workspace', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
                    'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
                ],
                'status' => 'active',
                'featured' => false,
                'rating' => 4.5,
                'review_count' => 678,
            ],
            [
                'name' => 'Nashville Music Row Inn',
                'description' => 'Historic inn on famous Music Row. Where country music legends have stayed. Walking distance to Grand Ole Opry and major music venues. Southern hospitality at its finest.',
                'type' => 'Inn',
                'address' => '1234 Music Row',
                'city' => 'Nashville',
                'state' => 'TN',
                'country' => 'USA',
                'latitude' => 36.1516,
                'longitude' => -86.7979,
                'phone' => '+1-615-555-0100',
                'email' => 'info@musicrowinn.com',
                'website' => 'https://www.musicrowinn.com',
                'price_per_night' => 14999.00,
                'max_guests' => 2,
                'amenities' => ['WiFi', 'Breakfast Included', 'Parking', 'Historic Building', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=800',
                    'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800',
                ],
                'status' => 'active',
                'featured' => false,
                'rating' => 4.6,
                'review_count' => 823,
            ],
            [
                'name' => 'Chicago Blues Hotel',
                'description' => 'Upscale hotel celebrating Chicago\'s rich blues and jazz heritage. Live music in the lobby bar nightly. Premium location near Millennium Park and major concert venues.',
                'type' => 'Hotel',
                'address' => '200 North Michigan Avenue',
                'city' => 'Chicago',
                'state' => 'IL',
                'country' => 'USA',
                'latitude' => 41.8866,
                'longitude' => -87.6243,
                'phone' => '+1-312-555-0100',
                'email' => 'reservations@chicagoblueshotel.com',
                'website' => 'https://www.chicagoblueshotel.com',
                'price_per_night' => 22999.00,
                'max_guests' => 3,
                'amenities' => ['WiFi', 'Restaurant', 'Bar', 'Live Music', 'Gym', 'Valet Parking', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
                    'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
                ],
                'status' => 'active',
                'featured' => true,
                'rating' => 4.8,
                'review_count' => 1456,
            ],
            [
                'name' => 'Seattle Grunge Apartments',
                'description' => 'Modern apartments in Capitol Hill, the birthplace of grunge. Vintage music posters and records in each unit. Close to historic music venues and coffee shops.',
                'type' => 'Apartment',
                'address' => '1500 East Pike Street',
                'city' => 'Seattle',
                'state' => 'WA',
                'country' => 'USA',
                'latitude' => 47.6144,
                'longitude' => -122.3129,
                'phone' => '+1-206-555-0100',
                'email' => 'info@seattlegrungeapts.com',
                'website' => 'https://www.seattlegrungeapts.com',
                'price_per_night' => 13999.00,
                'max_guests' => 4,
                'amenities' => ['WiFi', 'Kitchen', 'Washer/Dryer', 'Parking', 'Pet Friendly', 'Air Conditioning'],
                'images' => [
                    'https://images.unsplash.com/photo-1502672260066-6bc35f0332c0?w=800',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                ],
                'status' => 'active',
                'featured' => false,
                'rating' => 4.3,
                'review_count' => 534,
            ],
        ];

        foreach ($accommodations as $accommodation) {
            Accommodation::create($accommodation);
        }
    }
}

