<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehicle;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('vehicles')->delete();

        $vehicles = [
            [
                'registration_number' => 'KAB 123A',
                'make' => 'Toyota',
                'model' => 'Hiace',
                'year' => 2020,
                'type' => 'minibus',
                'capacity' => 14,
                'price_per_km' => 85.00,
                'driver_name' => 'John Kamau',
                'driver_phone' => '+254712345678',
                'driver_license' => 'DL123456',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System', 'USB Charging']),
                'description' => 'Comfortable minibus perfect for small groups',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'KBC 456B',
                'make' => 'Nissan',
                'model' => 'Civilian',
                'year' => 2021,
                'type' => 'bus',
                'capacity' => 33,
                'price_per_km' => 120.00,
                'driver_name' => 'Michael Ochieng',
                'driver_phone' => '+254723456789',
                'driver_license' => 'DL234567',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System', 'TV Screens', 'Reclining Seats']),
                'description' => 'Spacious bus for larger groups',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'KCD 789C',
                'make' => 'Toyota',
                'model' => 'Noah',
                'year' => 2022,
                'type' => 'van',
                'capacity' => 8,
                'price_per_km' => 95.00,
                'driver_name' => 'David Mutiso',
                'driver_phone' => '+254734567890',
                'driver_license' => 'DL345678',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System']),
                'description' => 'Luxury van for VIP transport',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'KDE 012D',
                'make' => 'Mercedes',
                'model' => 'Sprinter',
                'year' => 2021,
                'type' => 'van',
                'capacity' => 12,
                'price_per_km' => 110.00,
                'driver_name' => 'Peter Wanjala',
                'driver_phone' => '+254745678901',
                'driver_license' => 'DL456789',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System', 'USB Charging', 'Luggage Space']),
                'description' => 'Premium van with extra luggage space',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'KDF 345E',
                'make' => 'Toyota',
                'model' => 'Land Cruiser',
                'year' => 2023,
                'type' => 'suv',
                'capacity' => 7,
                'price_per_km' => 150.00,
                'driver_name' => 'Samuel Kiplagat',
                'driver_phone' => '+254756789012',
                'driver_license' => 'DL567890',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System', 'Leather Seats', 'Off-road capability']),
                'description' => 'Luxury SUV for premium transport experience',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'KDG 678F',
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2022,
                'type' => 'suv',
                'capacity' => 5,
                'price_per_km' => 100.00,
                'driver_name' => 'James Mwangi',
                'driver_phone' => '+254767890123',
                'driver_license' => 'DL678901',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System']),
                'description' => 'Compact SUV for small groups',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'KHI 901G',
                'make' => 'Isuzu',
                'model' => 'Bus',
                'year' => 2020,
                'type' => 'bus',
                'capacity' => 45,
                'price_per_km' => 130.00,
                'driver_name' => 'Joseph Njoroge',
                'driver_phone' => '+254778901234',
                'driver_license' => 'DL789012',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System', 'TV Screens', 'Refreshments']),
                'description' => 'Large bus for big groups and events',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'registration_number' => 'KJK 234H',
                'make' => 'Toyota',
                'model' => 'Premio',
                'year' => 2023,
                'type' => 'sedan',
                'capacity' => 4,
                'price_per_km' => 80.00,
                'driver_name' => 'Robert Kimani',
                'driver_phone' => '+254789012345',
                'driver_license' => 'DL890123',
                'features' => json_encode(['WiFi', 'Air Conditioning', 'Music System']),
                'description' => 'Comfortable sedan for small groups',
                'is_available' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('vehicles')->insert($vehicles);
    }
}
